# Data Preprocessing

Notebook ini digunakan untuk membersihkan dan menggabungkan data ekonomi Indonesia dari World Bank.

In [3]:
import pandas as pd

In [4]:
exchange_rate = pd.read_csv("Exchange_Rate.csv")
exports = pd.read_csv("Exports.csv")
fdi = pd.read_csv("FDI.csv")
gdp_growth = pd.read_csv("GDP_Growth.csv")
imports = pd.read_csv("Imports.csv")
inflation = pd.read_csv("Inflation.csv")
population_growth = pd.read_csv("Population_Growth.csv")
unemployment = pd.read_csv("Unemployment.csv")

print("Semua dataset berhasil dibaca")

Semua dataset berhasil dibaca

In [14]:
exchange_rate.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1991,1992,1993,1994,1995,1996,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Indonesia,IDN,"Official exchange rate (LCU per US$, period av...",PA.NUS.FCRF,1950.3175,2029.920833,2087.103867,2160.753675,2248.607975,2342.296292,...,13389.41294,13308.3268,13380.83388,14236.93877,14147.67136,14582.20347,14308.1439,14849.85394,15236.88466,15855.44829

In [15]:
gdp_long = pd.melt(
    gdp_growth,
    id_vars=[
        "Country Name",
        "Country Code",
        "Indicator Name",
        "Indicator Code"
    ],
    var_name="Year",
    value_name="GDP_Growth"
)

gdp_long.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,GDP_Growth
0,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1991,6.911983
1,NaN,NaN,NaN,NaN,1991,NaN
2,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1992,6.497507
3,NaN,NaN,NaN,NaN,1992,NaN
4,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1993,6.496408

In [16]:
gdp_long = gdp_long.dropna()

gdp_long.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,GDP_Growth
0,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1991,6.911983
2,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1992,6.497507
4,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1993,6.496408
6,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1994,7.539971
8,Indonesia,IDN,GDP growth (annual %),NY'GDP'MKTP'KD'ZG,1995,8.220007

In [17]:
def transform_data(df, value_name):
    df_long = pd.melt(
        df,
        id_vars=[
            "Country Name",
            "Country Code",
            "Indicator Name",
            "Indicator Code"
        ],
        var_name="Year",
        value_name=value_name
    )

    return df_long.dropna()

In [18]:
exchange_long = transform_data(exchange_rate, "Exchange_Rate")
exports_long = transform_data(exports, "Exports")
fdi_long = transform_data(fdi, "FDI")
gdp_long = transform_data(gdp_growth, "GDP_Growth")
imports_long = transform_data(imports, "Imports")
inflation_long = transform_data(inflation, "Inflation")
population_long = transform_data(population_growth, "Population_Growth")
unemployment_long = transform_data(unemployment, "Unemployment")

print("Semua dataset berhasil ditransformasi")

Semua dataset berhasil ditransformasi

In [19]:
exchange_long.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Exchange_Rate
0,Indonesia,IDN,"Official exchange rate (LCU per US$, period av...",PA.NUS.FCRF,1991,1950.317500
1,Indonesia,IDN,"Official exchange rate (LCU per US$, period av...",PA.NUS.FCRF,1992,2029.920833
2,Indonesia,IDN,"Official exchange rate (LCU per US$, period av...",PA.NUS.FCRF,1993,2087.103867
3,Indonesia,IDN,"Official exchange rate (LCU per US$, period av...",PA.NUS.FCRF,1994,2160.753675
4,Indonesia,IDN,"Official exchange rate (LCU per US$, period av...",PA.NUS.FCRF,1995,2248.607975

In [20]:
dataset = exchange_long[["Year", "Exchange_Rate"]]

dataset = dataset.merge(
    exports_long[["Year", "Exports"]],
    on="Year"
)

dataset = dataset.merge(
    fdi_long[["Year", "FDI"]],
    on="Year"
)

dataset = dataset.merge(
    gdp_long[["Year", "GDP_Growth"]],
    on="Year"
)

dataset = dataset.merge(
    imports_long[["Year", "Imports"]],
    on="Year"
)

dataset = dataset.merge(
    inflation_long[["Year", "Inflation"]],
    on="Year"
)

dataset = dataset.merge(
    population_long[["Year", "Population_Growth"]],
    on="Year"
)

dataset = dataset.merge(
    unemployment_long[["Year", "Unemployment"]],
    on="Year"
)

dataset.head()

,Year,Exchange_Rate,Exports,FDI,GDP_Growth,Imports,Inflation,Population_Growth,Unemployment
0,1991,1950.317500,28.351261,1.270772,6.911983,26.488304,9.419068,1.770137,2.617
1,1992,2029.920833,30.307464,1.387989,6.497507,27.119971,7.523510,1.733226,2.734
2,1993,2087.103867,26.754813,1.268301,6.496408,23.768572,9.671911,1.701584,2.782
3,1994,2160.753675,26.511428,1.192252,7.539971,25.365673,8.531998,1.685952,4.366
4,1995,2248.607975,26.312165,2.150080,8.220007,27.646425,9.420303,1.662785,4.611

In [21]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               34 non-null     object
 1   Exchange_Rate      34 non-null     float64
 2   Exports            34 non-null     float64
 3   FDI                34 non-null     float64
 4   GDP_Growth         34 non-null     float64
 5   Imports            34 non-null     float64
 6   Inflation          34 non-null     float64
 7   Population_Growth  34 non-null     float64
 8   Unemployment       34 non-null     float64
dtypes: float64(8), object(1)
memory usage: 2.5+ KB

In [22]:
dataset = dataset.dropna()

dataset.isnull().sum()

Year                 0
Exchange_Rate        0
Exports              0
FDI                  0
GDP_Growth           0
Imports              0
Inflation            0
Population_Growth    0
Unemployment         0
dtype: int64

In [23]:
dataset.to_csv("dataset_clean.csv", index=False)
dataset.to_csv("dataset_indonesia.csv", index=False)

print("Dataset berhasil disimpan")

Dataset berhasil disimpan